version: 2
jobs:
  build:
    working_directory: ~/ixmp
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: ls
          command: pwd && ls
      - run:
          name: Build App Docker Image
          command: docker build -t ixmp/ixmp:latest .
      - run:
          name: Python2 Tests
          command: docker run ixmp/ixmp:latest python2 -m pytest /ixmp/tests
      - run:
          name: Python3 Tests
          command: docker run ixmp/ixmp:latest python3 -m pytest /ixmp/tests
      