version: 2
jobs:
  build:
    working_directory: ~/ixmp_dev
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: ls
          command: pwd && ls
      - run:
          name: Build App Docker Image
          command: docker build -t message_ix/message_ix:latest .
      - run:
          name: Python2 Tests
          command: docker run message_ix/message_ix:latest python2 -m pytest /message_ix/tests
      - run:
          name: Python3 Tests
          command: docker run message_ix/message_ix:latest python3 -m pytest /message_ix/tests
      